name: epio CI Build

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'
  pull_request:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make emscripten python3 lcov
        
    - name: Build libepio
      run: |
        make

    - name: Build WASM
      run: |
        make wasm

    - name: Build and run hosted example
      run: |
        make clean
        make run-hosted-example

    - name: Build WASM example
      run: |
        make clean
        make wasm-example

    - name: Build firmware example
      run: |
        make -f example/firmware.mk

    - name: Run tests
      run: |
        make clean
        make test

    - name: Check code coverage
      run: |
        lcov --version
        make clean
        make cov