name: epio CI Build

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'
  pull_request:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make emscripten python3
        
    - name: Install latest lcov
      run: |
        sudo apt-get install -y perl libcapture-tiny-perl libjson-xs-perl libdatetime-perl
        git clone https://github.com/linux-test-project/lcov.git
        cd lcov
        git checkout v2.4
        make install PREFIX=$HOME/lcov-install
        echo "$HOME/lcov-install/bin" >> $GITHUB_PATH

    - name: Verify lcov installation
      run: |
        lcov --version

    - name: Build libepio
      run: |
        make

    - name: Build WASM
      run: |
        make wasm

    - name: Build and run hosted example
      run: |
        make clean
        make run-hosted-example

    - name: Build WASM example
      run: |
        make clean
        make wasm-example

    - name: Build firmware example
      run: |
        make -f example/firmware.mk

    - name: Run tests
      run: |
        make clean
        make test

    - name: Check code coverage
      run: |
        make cov